#lang info
(define collection "raylib")
(define deps '("base"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
(define scribblings '(("sys/docs/structs.scrbl" ())
                      ("sys/docs/enums.scrbl" ())
                      ("sys/docs/functions.scrbl" ())))
(define pkg-desc "Description Here")
(define version "0.0")
(define pkg-authors '(eutro))
(define license '(Apache-2.0 OR MIT))
