#lang racket/base

(require (except-in raylib/generated/unsafe/functions
                    SetClipboardText
                    GetClipboardText
                    WaitTime
                    GetRandomValue
                    SetRandomSeed
                    MemAlloc
                    MemRealloc
                    MemFree
                    CompressData
                    DecompressData
                    EncodeDataBase64
                    DecodeDataBase64
                    LoadFileData
                    LoadFileText
                    UnloadFileData
                    UnloadFileText
                    SaveFileData
                    SaveFileText
                    FileExists
                    DirectoryExists
                    IsFileExtension
                    GetFileExtension
                    GetFileName
                    GetFileNameWithoutExt
                    GetDirectoryPath
                    GetPrevDirectoryPath
                    GetWorkingDirectory
                    GetDirectoryFiles
                    ClearDirectoryFiles
                    ChangeDirectory
                    GetFileModTime
                    GetCodepointCount
                    GetCodepoint
                    CodepointToUTF8
                    TextCodepointsToUTF8
                    TextCopy
                    TextIsEqual
                    TextLength
                    TextFormat
                    TextSubtext
                    TextReplace
                    TextInsert
                    TextJoin
                    TextSplit
                    TextAppend
                    TextFindIndex
                    TextToUpper
                    TextToLower
                    TextToPascal
                    TextToInteger
                    SetTraceLogCallback
                    BeginVrStereoMode
                    BeginMode3D
                    EndVrStereoMode
                    EndMode3D
                    LoadVrStereoConfig
                    UnloadVrStereoConfig
                    DrawLine3D
                    DrawPoint3D
                    DrawCircle3D
                    DrawTriangle3D
                    DrawTriangleStrip3D
                    DrawCube
                    DrawCubeV
                    DrawCubeWires
                    DrawCubeWiresV
                    DrawCubeTexture
                    DrawCubeTextureRec
                    DrawSphere
                    DrawSphereEx
                    DrawSphereWires
                    DrawCylinder
                    DrawCylinderEx
                    DrawCylinderWires
                    DrawCylinderWiresEx
                    DrawPlane
                    DrawRay
                    DrawGrid
                    LoadModel
                    LoadModelFromMesh
                    UnloadModel
                    UnloadModelKeepMeshes
                    GetModelBoundingBox
                    DrawModel
                    DrawModelEx
                    DrawModelWires
                    DrawModelWiresEx
                    DrawBoundingBox
                    DrawBillboard
                    DrawBillboardRec
                    DrawBillboardPro
                    UploadMesh
                    UpdateMeshBuffer
                    UnloadMesh
                    DrawMesh
                    DrawMeshInstanced
                    ExportMesh
                    GetMeshBoundingBox
                    GenMeshTangents
                    GenMeshBinormals
                    GenMeshPoly
                    GenMeshPlane
                    GenMeshCube
                    GenMeshSphere
                    GenMeshHemiSphere
                    GenMeshCylinder
                    GenMeshCone
                    GenMeshTorus
                    GenMeshKnot
                    GenMeshHeightmap
                    GenMeshCubicmap
                    LoadMaterials
                    LoadMaterialDefault
                    UnloadMaterial
                    SetMaterialTexture
                    SetModelMeshMaterial
                    LoadModelAnimations
                    UpdateModelAnimation
                    UnloadModelAnimation
                    UnloadModelAnimations
                    IsModelAnimationValid
                    CheckCollisionSpheres
                    CheckCollisionBoxes
                    CheckCollisionBoxSphere
                    GetRayCollisionSphere
                    GetRayCollisionBox
                    GetRayCollisionMesh
                    GetRayCollisionTriangle
                    GetRayCollisionQuad)
         raylib/derived)

(provide (all-from-out raylib/generated/unsafe/functions
                       raylib/derived))
